package idh.c3cloud.tis.pilot

import org.junit.Test
import org.junit.runner.RunWith
import org.springframework.beans.factory.annotation.Autowired
import org.springframework.beans.factory.annotation.Value
import org.springframework.boot.test.context.SpringBootTest
import org.springframework.mail.SimpleMailMessage
import org.springframework.mail.javamail.JavaMailSender
import org.springframework.test.context.junit4.SpringRunner

@RunWith(SpringRunner::class)
@SpringBootTest
class EmailTest {
    @Autowired
    lateinit var emailSender: JavaMailSender

    @Value("\${email.to}")
    lateinit var to: String

    @Test
    fun sendEmail() {
        sendSimpleMessage(to, "[C3-Cloud] Patient Data Synchronization Error",
                "This is an automated notification generated by C3-Cloud TIS. ")
    }

    private fun sendSimpleMessage(to: String, subject: String, text: String) {
        val message = SimpleMailMessage()
        message.setTo(to)
        message.setSubject(subject)
        message.setText(text);
        emailSender.send(message);
    }

}