#debug: true
#logging.level.org.springframework.web.reactive.function.client.ExchangeFunctions: TRACE
#spring.http.log-request-details: true
#logging.file: logs/c3cloud-tis.log
logging:
    level:
        org.springframework: INFO #DEBUG
    file:
        max-size: 20MB
        max-history: 10
server:
    port: 80
spring:
    application:
        name: C3-Cloud TIS
    data:
        mongodb:
            database: tis
            host: localhost
            port: 27017
    jackson:
        default-property-inclusion: non_null
    security:
        oauth2:
            client:
                provider:
                    provider1:
                        token-uri: https://{{authoriser_url}}/protocol/openid-connect/token
                    provider2:
                        token-uri: https://{{authoriser_url}}/protocol/openid-connect/token
                    onauth:
                        token-uri: https://${c3dp.host}/c3cloud/onauth/api/token
                registration:
                    c3cloud-fhir:
                        authorization-grant-type: client_credentials
                        client-id: c3cloud-tis
                        client-secret: {{client_secret}}
                        provider: onauth
                        scope: user/*.*
                    provider1-services:
                        authorization-grant-type: client_credentials
                        client-id: {{cient_id}}
                        client-secret: {{client_secret}}
                        provider: provider1
                        scope: user/PatientList-read
                    provider2-services:
                        authorization-grant-type: client_credentials
                        client-id: {{client_id}}
                        client-secret: {{client_secret}}
                        provider: provider2
                        #scope: user/PatientList-read
        user:
            name: {{username}}
            password: {{password}}
    mail:
        host: smtp.gmail.com
        port: 587
        username: {{email_address}}
        password: {{password}}
        properties:
            mail:
                smtp:
                    starttls:
                        enable: true
                        required: true
                    auth: true
                    connectiontimeout: 5000
                    timeout: 5000
                    writetimeout: 5000
c3dp:
    host: {{care_planning_url}}
    fhir-uri: https://${c3dp.host}/c3cloud/fhir-secure/
    event-api-uri: https://${c3dp.host}/c3cloud/event/api/both
    incremental-loading: true
    missing-timestamp: ignore
structure-map:
    uri: http://{{structure_mapper_url}}/sms/transform
provider1:
    cda-uri: http://{{cda_url}}
    dbp-uri: http://{{dbp_url}}
task:
    pool:
        size: 20
email:
    notification: false
    from: {{email_address}}
    to: {{admin_email}}
